college/college/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^collegesite/',include('collegesite.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college/collegesite/urls.py
from django.conf.urls import url
from . import views


app_name = 'collegesite'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^student_application/$', views.student_application, name='student_application'),
    url(r'^student_registartion/$', views.student_registartion,name='student_registartion'),
    url(r'^staff_registration/$', views.staff_registration, name='staff_registration'),
    url(r'login/$', views.user_login, name='user_login'),
    url(r'logout/$', views.user_logout, name='user_logout'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^staff_profile/$', views.staff_profile, name ='staff_profile'),
    url(r'student_profile/$', views.student_profile, name='student_profile'),
    url(r'students/$', views.students, name="students"),
    #url(r'staff_department/$', views.staff, name='staff_department'),
    url(r'staff', views.staff, name='staff'),
    url(r'^student_login/$', views.student_login, name='student_login'),
]

college/collegesite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modeified_at = models.DateTimeField(auto_now_add=True)

    class meta:
        abstract = True

class Studentapplication(TimeStampedModel):

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others'),
    )

    DEPARTMENT_CHOICES = (
        ('CE', 'Civil Engineering'),
        ('CSE', 'Computer Science Engineering'),
        ('ECE', 'Electronics Communtication Engineering'),
        ('EEE', 'Electronics Electrical Engineering'),
        ('ME', 'Mechanical Engineering')
    )
    name = models.CharField(max_length=40)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    email = models.EmailField()
    dob = models.DateField()
    department = models.CharField(max_length=3, choices=DEPARTMENT_CHOICES)
    sccmemo = models.FileField()
    intermemo = models.FileField()
    address = models.TextField(max_length=100)
    nationality = models.CharField(max_length=20)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.name)


class Student(TimeStampedModel):

    name = models.OneToOneField(Studentapplication, on_delete=models.CASCADE, primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    father = models.CharField(max_length=40)
    mother = models.CharField(max_length=40)
    profilepic = models.ImageField()

    def __str__(self):
        return "{} {}".format(self.name.name, self.user.username)
    
class Staff(TimeStampedModel):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others'),
    )
    DEPARTMENT_CHOICES = (
        ('CE', 'Civil Engineering'),
        ('CSE', 'Computer Science Engineering'),
        ('ECE', 'Electronics Communtication Engineering'),
        ('EEE', 'Electronics Electrical Engineering'),
        ('ME', 'Mechanical Engineering')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    email = models.EmailField()
    age = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    department = models.CharField(max_length=3, choices=DEPARTMENT_CHOICES)
    profilepic = models.ImageField()

    def __str__(self):
        return "{} {}".format(self.name, self.user.username)

college/collegesite/forms.py
from django import forms
from .models import User,  Student, Staff


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username','password','email')



class StudentregistartionForm(forms.ModelForm):

    class Meta:
        model = Student
        exclude = ['user','name']


class StaffuserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'password',)



class StaffregistrationForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ('name','email', 'age', 'gender', 'department', 'profilepic' )

college/collegesite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Studentapplication, Student, User, Staff
from django.contrib.auth.backends import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import UserForm, StudentregistartionForm, StaffuserForm, StaffregistrationForm
# Create your views here.


def index(request):
    return render(request, 'collegesite/base.html', {})


def student_application(request):
    if  request.method == 'POST':
        Studentapplication.objects.create(
            name = request.POST['name'],
            gender = request.POST['gender'],
            email = request.POST['email'],
            dob = request.POST['dob'],
            address = request.POST['address'],
            nationality = request.POST['nationality'],
            department = request.POST['department'],
            sccmemo = request.FILES['sscmemo'],
            intermemo = request.FILES['intermemo'],

                )
        return HttpResponseRedirect(reverse('collegesite:index'))
    return render(request, 'collegesite/student_application.html', {})


def student_registartion(request):
    if request.method == "GET":
        form1 = UserForm()
        form2 = StudentregistartionForm()
        return render(request, 'collegesite/student_registartion.html', {'form1':form1, 'form2':form2})
    form1 = UserForm(request.POST)
    form2 = StudentregistartionForm(request.POST, request.FILES)
    email = request.POST['email']
    studenta = Studentapplication.objects.filter(email=email, is_verified=True)
    studentb = Studentapplication.objects.get(email=email, is_verified=True)
    if studenta.exists() and form2.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        user = User.objects.create_user(username,email,password)
        profile = form2.save(commit=False)
        profile.user = user
        profile.name = studentb
        profile.save()
        return HttpResponseRedirect(reverse('collegesite:index'))
    return render(request, 'collegesite/student_registartion.html', {'form1':form1, 'form2':form2})


def staff_registration(request):
    if request.method == 'POST':

        form1 = StaffuserForm(request.POST)
        form2 = StaffregistrationForm(request.POST,request.FILES)
        if form1.is_valid() and form2.is_valid():
                username = request.POST['username']
                password = request.POST['password']
                email = request.POST['email']
                user = User.objects.create_user(username,email,password)
                profile = form2.save(commit=False)
                #import ipdb; ipdb.set_trace()
                profile.user = user
                profile.save()
                return HttpResponseRedirect(reverse('collegesite:index'))
    else:
        form1 = StaffuserForm()
        form2 = StaffregistrationForm()
    return render(request, 'collegesite/staff_registration.html', {'form1':form1,'form2':form2})


@login_required
def student_profile(request):
    stnd = Student.objects.get(user__username=request.user)
    return render(request, 'collegesite/student_profile.html', {'stnd': stnd})


@login_required
def staff_profile(request):
    s = Staff.objects.get(user__username=request.user.username)
    return render(request, 'collegesite/staff_profile.html', {'s': s})


def student_list(request):
    list_of_selected_students = Studentapplication.objects.filter(is_verified=True)
    return render(request, 'collegesite/student_list.html', {'list_of_selected_students':list_of_selected_students})


def user_login(request):

    if request.method == "POST":
        import ipdb
        ipdb.set_trace()
        username = request.POST['username']
        password = request.POST['password']
        #s = Studentapplication.objects.get(email__email, is_verified=True)
        #import ipdb; ipdb.set_trace()
        user = authenticate(request, username=username, password=password)

        if user is not None:


            login(request,user)

            return HttpResponseRedirect(reverse('collegesite:staff_profile'))

        else:
            return render(request, 'collegesite/login.html', {})
    else:
        return render(request, 'collegesite/login.html', {})


def student_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        #s = Studentapplication.objects.get(email__email, is_verified=True)

        user = authenticate(request, username=username, password=password)
        if user is not None:


            login(request,user)

            return HttpResponseRedirect(reverse('collegesite:student_profile'))

        else:
            return render(request, 'collegesite/login.html', {})
    else:
        return render(request, 'collegesite/login.html', {})

def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('collegesite:index'))


@login_required
def staff(request):
    staffs = Staff.objects.all()
    return render(request, 'collegesite/staff_all.html', {'staffs':staffs})
@login_required
def students(request):
    students = Student.objects.all()
    return render(request, 'collegesite/students.html', {'students': students})

"""
@login_required
def staff_department(request): 
    staff_deparment = Staff.objects.filter(deparmenet= user.deparment)
    return render(request, 'college/staff_department', {'staff_department' : staff_deparment})
"""

college/collegesite/templates/collegesite/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collegesite</title>
    <link href="{% static "css" %}" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <div class="nav-header">
            <a class="navbar-brand" href="/">college</a>
        </div>
  </div>
</nav>

<div list>
<ul>

    <a href="{% url 'collegesite:staff_registration' %}">Staff Registration</a><br>
    <a href="{% url 'collegesite:user_login' %}">Login</a><br>
    <a href="{% url 'collegesite:student_application' %}">Student Application</a><br>
    <a href="{% url 'collegesite:student_login' %}">student login</a><br>
    <a href="{% url 'collegesite:student_registartion' %}">Student Registartion</a><br>
    <a href="{% url 'collegesite:student_list' %}">Sortlisted Students applications</a><br>
</ul>
</div>

</body>
</html>

college/collegesite/templates/collegesite/login.html
<form action = "." method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <!--email : <input type="email"  name="email"> -->
    username : <input type="text" name="username" ><br>
    password : <input type="password" name="password"><br>
    <input type="submit" value="Login">
</form>

college/collegesite/templates/collegesite/staff_all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for staff in staffs %}
<table style ="width:100%">
<tr>
    <td>Name</td>
    <td>Email</td>
    <td>Department</td>
<tr>
 <tr>
    <td>{{stafft.name}}</td>
    <td>{{staff.email}}</td>
    <td>{{staff.department}}</td>
  <tr>
    </table>
    {% endfor %}

</body>
</html>

college/collegesite/templates/collegesite/staff_department.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for staff in staff_deparment %}
<table style ="width:100%">
<tr>
    <td>Name</td>
    <td>Email</td>
    <td>Department</td>
<tr>
 <tr>
    <td>{{staff.name}}</td>
    <td>{{staff.email}}</td>
    <td>{{stafft.department}}</td>
  <tr>
    </table>
    {% endfor %}

</body>
</html>

college/collegesite/templates/collegesite/staff_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Name:{{s.name}}</p><br>
<img src="{{s.profilepic}}" ><br><br>
<p>Email:{{s.email}}</p><br>
<p>Age:{{s.age}}</p><br>
<p>Gender:{{s.gender}}</p><br>
<p>Department:{{s.department}}</p>


<a href="{% url 'collegesite:staff' %}">Staff</a>
<a href="{% url 'collegesite:students' %}">Students</a>
<a href = "{% url 'collegesite:user_logout' %}">Logout</a>
</body>
</html>

college/collegesite/templates/collegesite/staff_registration.html
<form action="{% url 'collegesite:staff_registration' %}" method="post" enctype="multipart/form-data">
   {% csrf_token %}
  {% for field in form1 %}
  <div class="fieldWrapper">
    {{ field.label_tag }} {{ field }}
  </div>
  {% endfor %}
  {% csrf_token %}
  {% for field in form2 %}
  <div class="fieldWrapper">
    {{ field.label_tag }} {{ field }}
  </div>
  {% endfor %}

  <button type="submit">submit</button>
</form>

college/collegesite/templates/collegesite/student_application.html
{% extends "collegesite/base.html" %}

{% block child_block %}
<form class="" action="{% url 'collegesite:student_application' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  Name: <input type="text" name="name"><br><br>
  Gender: <select name="gender">
    <option value="M">Male</option>
    <option value="F">Female</option>
    <option value="O">Others</option>
  </select>
  Email : <input type="email" name="email"><br><br>
  Date of Birth : <input type="date" name="dob"><br><br>
  Address : <input type="text" name="address"><br><br>
  Nationality : <input type="text" name="nationality"><br><br>
  SSC Memo: <input type="file" name="sscmemo"><br><br>
  Intermediate Memo: <input type="file" name="intermemo"><br><br>
  Department :<select name="department">
    <option value="CE">Civil Engineering</option>
    <option value="CSE">Computer Science Engineering</option>
    <option value="ECE">Electronics Communtication Engineering</option>
    <option value="EEE">Electrical Electronics Engineering</option>
    <option value="ME">Mechanical Engineering</option>
  </select>

  <input type="submit" value="submit" />
  {% endblock %}
</form>

college/collegesite/templates/collegesite/student_list.html
{% for student in list_of_selected_students %}
<table style ="width:100%">
<tr>
    <td>Name</td>
    <td>Email</td>
    <td>Department</td>
<tr>
 <tr>
    <td>{{student.name}}</td>
    <td>{{student.email}}</td>
    <td>{{student.department}}</td>
  <tr>
    </table>
    {% endfor %}

college/collegesite/templates/collegesite/student_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action = "." method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    username : <input type="text" name="username" ><br>
    password : <input type="password" name="password"><br>
    <input type="submit" value="Login">
</form>

</body>
</html>

college/collegesite/templates/collegesite/student_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Name:{{stnd.name}}</p><br>
<img src="{{stnd.profilepic}}" ><br><br>
<p>Email:{{stnd.email}}</p><br>
<p>Age:{{stnd.age}}</p><br>
<p>Date of Birth:{{stnd.name.dob}}</p>
<p>Gender:{{stnd.name.gender}}</p><br>
<p>Father Name:{{stnd.father}}</p><br>
<p>Mother Name:{{stnd.mother}}</p><br>
<p>Nationality:{{stnd.name.nationality}}</p>
<p>SSC Memo:{{stnd.name.sccmemo}}</p><br>
<p>Intermediate Memo:{{stnd.name.intermemo.url}}</p><br>
<p>Department:{{stnd.name.department.url}}</p><br>


<a href = "{% url 'collegesite:user_logout' %}">Logout</a>
</body>
</html>

college/collegesite/templates/collegesite/student_registartion.html
<form action="{% url 'collegesite:student_registartion' %}" method="post" enctype="multipart/form-data">
   {% csrf_token %}
  {% for field in form1 %}
  <div class="fieldWrapper">
    {{ field.label_tag }} {{ field }}
  </div>
  {% endfor %}
  {% csrf_token %}
  {% for field in form2 %}
  <div class="fieldWrapper">
    {{ field.label_tag }} {{ field }}
  </div>
  {% endfor %}

  <button type="submit">submit</button>
</form>

college/collegesite/templates/collegesite/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for student in students %}
<table style ="width:100%">
<tr>
    <td>Name</td>
    <td>Email</td>
    <td>Department</td>
<tr>
 <tr>
    <td>{{student.name}}</td>
    <td>{{student.name.email}}</td>
    <td>{{student.name.department}}</td>
  <tr>
    </table>
{% endfor %}
</body>
</html>